/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cargo {
  'id' : bigint,
  'status' : CargoStatus,
  'name' : string,
  'perishabilityRate' : bigint,
  'totalWeight' : bigint,
}
export type CargoStatus = { 'spoiling' : null } |
  { 'fresh' : null } |
  { 'spoiled' : null };
export interface DeliveryRecord {
  'cargoName' : string,
  'player' : UserId,
  'gameId' : GameId,
  'deliveryTime' : bigint,
  'landedAtMogadishu' : boolean,
  'score' : bigint,
  'freshnessPercent' : bigint,
  'timestamp' : Timestamp,
}
export type GameId = bigint;
export type GamePhase = { 'preparing' : null } |
  { 'takingOff' : null } |
  { 'flying' : null } |
  { 'delivered' : null } |
  { 'landing' : null };
export interface GameState {
  'id' : GameId,
  'startTime' : Timestamp,
  'endTime' : [] | [Timestamp],
  'player' : UserId,
  'cargo' : Cargo,
  'altitude' : bigint,
  'speed' : bigint,
  'distanceRemaining' : bigint,
  'phase' : GamePhase,
}
export interface LeaderboardEntry {
  'player' : UserId,
  'bestDeliveryTime' : bigint,
  'rank' : bigint,
  'deliveriesCount' : bigint,
  'totalScore' : bigint,
}
export interface Score {
  'player' : UserId,
  'gameId' : GameId,
  'deliveryTime' : bigint,
  'totalScore' : bigint,
  'freshnessPercent' : bigint,
  'timestamp' : Timestamp,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface _SERVICE {
  '__activeGames' : ActorMethod<
    [[] | [GameId], [] | [bigint]],
    Array<[GameId, GameState]>
  >,
  '__deliveryRecords' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<DeliveryRecord>
  >,
  '__nextGameId' : ActorMethod<[], any>,
  'getDeliveryHistory' : ActorMethod<[UserId, bigint], Array<DeliveryRecord>>,
  'getGameState' : ActorMethod<[GameId], [] | [GameState]>,
  'getLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'startDelivery' : ActorMethod<[Cargo], GameState>,
  'submitScore' : ActorMethod<[GameId, boolean], [] | [Score]>,
  'updateGameState' : ActorMethod<
    [GameId, bigint, bigint, bigint],
    [] | [GameState]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];