/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameId = IDL.Nat;
export const Timestamp = IDL.Nat;
export const UserId = IDL.Principal;
export const CargoStatus = IDL.Variant({
  'spoiling' : IDL.Null,
  'fresh' : IDL.Null,
  'spoiled' : IDL.Null,
});
export const Cargo = IDL.Record({
  'id' : IDL.Nat,
  'status' : CargoStatus,
  'name' : IDL.Text,
  'perishabilityRate' : IDL.Nat,
  'totalWeight' : IDL.Nat,
});
export const GamePhase = IDL.Variant({
  'preparing' : IDL.Null,
  'takingOff' : IDL.Null,
  'flying' : IDL.Null,
  'delivered' : IDL.Null,
  'landing' : IDL.Null,
});
export const GameState = IDL.Record({
  'id' : GameId,
  'startTime' : Timestamp,
  'endTime' : IDL.Opt(Timestamp),
  'player' : UserId,
  'cargo' : Cargo,
  'altitude' : IDL.Nat,
  'speed' : IDL.Nat,
  'distanceRemaining' : IDL.Nat,
  'phase' : GamePhase,
});
export const DeliveryRecord = IDL.Record({
  'cargoName' : IDL.Text,
  'player' : UserId,
  'gameId' : GameId,
  'deliveryTime' : IDL.Nat,
  'landedAtMogadishu' : IDL.Bool,
  'score' : IDL.Nat,
  'freshnessPercent' : IDL.Nat,
  'timestamp' : Timestamp,
});
export const LeaderboardEntry = IDL.Record({
  'player' : UserId,
  'bestDeliveryTime' : IDL.Nat,
  'rank' : IDL.Nat,
  'deliveriesCount' : IDL.Nat,
  'totalScore' : IDL.Nat,
});
export const Score = IDL.Record({
  'player' : UserId,
  'gameId' : GameId,
  'deliveryTime' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'freshnessPercent' : IDL.Nat,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  '__activeGames' : IDL.Func(
      [IDL.Opt(GameId), IDL.Opt(IDL.Nat)],
      [IDL.Vec(IDL.Tuple(GameId, GameState))],
      ['query'],
    ),
  '__deliveryRecords' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(DeliveryRecord)],
      ['query'],
    ),
  '__nextGameId' : IDL.Func([], [IDL.Reserved], ['query']),
  'getDeliveryHistory' : IDL.Func(
      [UserId, IDL.Nat],
      [IDL.Vec(DeliveryRecord)],
      ['query'],
    ),
  'getGameState' : IDL.Func([GameId], [IDL.Opt(GameState)], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'startDelivery' : IDL.Func([Cargo], [GameState], []),
  'submitScore' : IDL.Func([GameId, IDL.Bool], [IDL.Opt(Score)], []),
  'updateGameState' : IDL.Func(
      [GameId, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Opt(GameState)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameId = IDL.Nat;
  const Timestamp = IDL.Nat;
  const UserId = IDL.Principal;
  const CargoStatus = IDL.Variant({
    'spoiling' : IDL.Null,
    'fresh' : IDL.Null,
    'spoiled' : IDL.Null,
  });
  const Cargo = IDL.Record({
    'id' : IDL.Nat,
    'status' : CargoStatus,
    'name' : IDL.Text,
    'perishabilityRate' : IDL.Nat,
    'totalWeight' : IDL.Nat,
  });
  const GamePhase = IDL.Variant({
    'preparing' : IDL.Null,
    'takingOff' : IDL.Null,
    'flying' : IDL.Null,
    'delivered' : IDL.Null,
    'landing' : IDL.Null,
  });
  const GameState = IDL.Record({
    'id' : GameId,
    'startTime' : Timestamp,
    'endTime' : IDL.Opt(Timestamp),
    'player' : UserId,
    'cargo' : Cargo,
    'altitude' : IDL.Nat,
    'speed' : IDL.Nat,
    'distanceRemaining' : IDL.Nat,
    'phase' : GamePhase,
  });
  const DeliveryRecord = IDL.Record({
    'cargoName' : IDL.Text,
    'player' : UserId,
    'gameId' : GameId,
    'deliveryTime' : IDL.Nat,
    'landedAtMogadishu' : IDL.Bool,
    'score' : IDL.Nat,
    'freshnessPercent' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  const LeaderboardEntry = IDL.Record({
    'player' : UserId,
    'bestDeliveryTime' : IDL.Nat,
    'rank' : IDL.Nat,
    'deliveriesCount' : IDL.Nat,
    'totalScore' : IDL.Nat,
  });
  const Score = IDL.Record({
    'player' : UserId,
    'gameId' : GameId,
    'deliveryTime' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'freshnessPercent' : IDL.Nat,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    '__activeGames' : IDL.Func(
        [IDL.Opt(GameId), IDL.Opt(IDL.Nat)],
        [IDL.Vec(IDL.Tuple(GameId, GameState))],
        ['query'],
      ),
    '__deliveryRecords' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(DeliveryRecord)],
        ['query'],
      ),
    '__nextGameId' : IDL.Func([], [IDL.Reserved], ['query']),
    'getDeliveryHistory' : IDL.Func(
        [UserId, IDL.Nat],
        [IDL.Vec(DeliveryRecord)],
        ['query'],
      ),
    'getGameState' : IDL.Func([GameId], [IDL.Opt(GameState)], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'startDelivery' : IDL.Func([Cargo], [GameState], []),
    'submitScore' : IDL.Func([GameId, IDL.Bool], [IDL.Opt(Score)], []),
    'updateGameState' : IDL.Func(
        [GameId, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Opt(GameState)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };