/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Cargo {
    id: bigint;
    status: CargoStatus;
    name: string;
    perishabilityRate: bigint;
    totalWeight: bigint;
}
export type UserId = Principal;
export type Timestamp = bigint;
export interface LeaderboardEntry {
    player: UserId;
    bestDeliveryTime: bigint;
    rank: bigint;
    deliveriesCount: bigint;
    totalScore: bigint;
}
export interface DeliveryRecord {
    cargoName: string;
    player: UserId;
    gameId: GameId;
    deliveryTime: bigint;
    landedAtMogadishu: boolean;
    score: bigint;
    freshnessPercent: bigint;
    timestamp: Timestamp;
}
export type GameId = bigint;
export interface Score {
    player: UserId;
    gameId: GameId;
    deliveryTime: bigint;
    totalScore: bigint;
    freshnessPercent: bigint;
    timestamp: Timestamp;
}
export interface GameState {
    id: GameId;
    startTime: Timestamp;
    endTime?: Timestamp;
    player: UserId;
    cargo: Cargo;
    altitude: bigint;
    speed: bigint;
    distanceRemaining: bigint;
    phase: GamePhase;
}
export enum CargoStatus {
    spoiling = "spoiling",
    fresh = "fresh",
    spoiled = "spoiled"
}
export enum GamePhase {
    preparing = "preparing",
    takingOff = "takingOff",
    flying = "flying",
    delivered = "delivered",
    landing = "landing"
}
export interface backendInterface {
    __activeGames(ko: GameId | null, count: bigint | null): Promise<Array<[GameId, GameState]>>;
    __deliveryRecords(io: bigint | null, count: bigint | null): Promise<Array<DeliveryRecord>>;
    __nextGameId(): Promise<any>;
    getDeliveryHistory(player: UserId, limit: bigint): Promise<Array<DeliveryRecord>>;
    getGameState(gameId: GameId): Promise<GameState | null>;
    getLeaderboard(limit: bigint): Promise<Array<LeaderboardEntry>>;
    startDelivery(cargo: Cargo): Promise<GameState>;
    submitScore(gameId: GameId, landedAtMogadishu: boolean): Promise<Score | null>;
    updateGameState(gameId: GameId, speed: bigint, altitude: bigint, distanceRemaining: bigint): Promise<GameState | null>;
}
import type { Cargo as _Cargo, CargoStatus as _CargoStatus, GameId as _GameId, GamePhase as _GamePhase, GameState as _GameState, Score as _Score, Timestamp as _Timestamp, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __activeGames(arg0: GameId | null, arg1: bigint | null): Promise<Array<[GameId, GameState]>> {
        if (this.processError) {
            try {
                const result = await this.actor.__activeGames(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__activeGames(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async __deliveryRecords(arg0: bigint | null, arg1: bigint | null): Promise<Array<DeliveryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.__deliveryRecords(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__deliveryRecords(to_candid_opt_n2(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __nextGameId(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextGameId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextGameId();
            return result;
        }
    }
    async getDeliveryHistory(arg0: UserId, arg1: bigint): Promise<Array<DeliveryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveryHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveryHistory(arg0, arg1);
            return result;
        }
    }
    async getGameState(arg0: GameId): Promise<GameState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGameState(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGameState(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: bigint): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(arg0);
            return result;
        }
    }
    async startDelivery(arg0: Cargo): Promise<GameState> {
        if (this.processError) {
            try {
                const result = await this.actor.startDelivery(to_candid_Cargo_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_GameState_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startDelivery(to_candid_Cargo_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_GameState_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitScore(arg0: GameId, arg1: boolean): Promise<Score | null> {
        if (this.processError) {
            try {
                const result = await this.actor.submitScore(arg0, arg1);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitScore(arg0, arg1);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGameState(arg0: GameId, arg1: bigint, arg2: bigint, arg3: bigint): Promise<GameState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGameState(arg0, arg1, arg2, arg3);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGameState(arg0, arg1, arg2, arg3);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CargoStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CargoStatus): CargoStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Cargo_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cargo): Cargo {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_GamePhase_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GamePhase): GamePhase {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_GameState_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GameState): GameState {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GameState]): GameState | null {
    return value.length === 0 ? null : from_candid_GameState_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Score]): Score | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _GameId;
    startTime: _Timestamp;
    endTime: [] | [_Timestamp];
    player: _UserId;
    cargo: _Cargo;
    altitude: bigint;
    speed: bigint;
    distanceRemaining: bigint;
    phase: _GamePhase;
}): {
    id: GameId;
    startTime: Timestamp;
    endTime?: Timestamp;
    player: UserId;
    cargo: Cargo;
    altitude: bigint;
    speed: bigint;
    distanceRemaining: bigint;
    phase: GamePhase;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        endTime: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.endTime)),
        player: value.player,
        cargo: from_candid_Cargo_n8(_uploadFile, _downloadFile, value.cargo),
        altitude: value.altitude,
        speed: value.speed,
        distanceRemaining: value.distanceRemaining,
        phase: from_candid_GamePhase_n12(_uploadFile, _downloadFile, value.phase)
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _CargoStatus;
    name: string;
    perishabilityRate: bigint;
    totalWeight: bigint;
}): {
    id: bigint;
    status: CargoStatus;
    name: string;
    perishabilityRate: bigint;
    totalWeight: bigint;
} {
    return {
        id: value.id,
        status: from_candid_CargoStatus_n10(_uploadFile, _downloadFile, value.status),
        name: value.name,
        perishabilityRate: value.perishabilityRate,
        totalWeight: value.totalWeight
    };
}
function from_candid_tuple_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_GameId, _GameState]): [GameId, GameState] {
    return [
        value[0],
        from_candid_GameState_n5(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spoiling: null;
} | {
    fresh: null;
} | {
    spoiled: null;
}): CargoStatus {
    return "spoiling" in value ? CargoStatus.spoiling : "fresh" in value ? CargoStatus.fresh : "spoiled" in value ? CargoStatus.spoiled : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    takingOff: null;
} | {
    flying: null;
} | {
    delivered: null;
} | {
    landing: null;
}): GamePhase {
    return "preparing" in value ? GamePhase.preparing : "takingOff" in value ? GamePhase.takingOff : "flying" in value ? GamePhase.flying : "delivered" in value ? GamePhase.delivered : "landing" in value ? GamePhase.landing : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[_GameId, _GameState]>): Array<[GameId, GameState]> {
    return value.map((x)=>from_candid_tuple_n4(_uploadFile, _downloadFile, x));
}
function to_candid_CargoStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CargoStatus): _CargoStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_Cargo_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cargo): _Cargo {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GameId | null): [] | [_GameId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: CargoStatus;
    name: string;
    perishabilityRate: bigint;
    totalWeight: bigint;
}): {
    id: bigint;
    status: _CargoStatus;
    name: string;
    perishabilityRate: bigint;
    totalWeight: bigint;
} {
    return {
        id: value.id,
        status: to_candid_CargoStatus_n17(_uploadFile, _downloadFile, value.status),
        name: value.name,
        perishabilityRate: value.perishabilityRate,
        totalWeight: value.totalWeight
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CargoStatus): {
    spoiling: null;
} | {
    fresh: null;
} | {
    spoiled: null;
} {
    return value == CargoStatus.spoiling ? {
        spoiling: null
    } : value == CargoStatus.fresh ? {
        fresh: null
    } : value == CargoStatus.spoiled ? {
        spoiled: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
